#include "instructions.h"

int ADD_Imm_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int ADD_Imm_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int ADD_Imm_T3(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int ADD_Imm_T4(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int ADD_Reg_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int ADD_Reg_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int ADD_Reg_T3(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int B_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int B_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int B_T3(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int B_T4(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int BL_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int BX_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int CMP_Imm_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int CMP_Imm_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int CMP_Reg_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int CMP_Reg_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int CMP_Reg_T3(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int IT_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int LDR_Imm_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int LDR_Imm_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int LDR_Imm_T3(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int LDR_Imm_T4(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int LDR_Lit_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int LDR_Lit_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int MOV_Imm_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int MOV_Imm_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int MOV_Imm_T3(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int MOV_Reg_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int MOV_Reg_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int MOV_Reg_T3(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int MOVT_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int MUL_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int MUL_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int POP_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int POP_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int POP_T3(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int PUSH_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int PUSH_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int PUSH_T3(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int STR_Imm_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int STR_Imm_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int STR_Imm_T3(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int STR_Imm_T4(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int STR_Reg_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int STR_Reg_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int SUB_Imm_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int SUB_Imm_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int SUB_Imm_T3(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int SUB_Imm_T4(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int SUB_Reg_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int SUB_Reg_T2(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
int SVC_T1(word binary, memory mem, int* in_it, unsigned int* it_state) {return 0;}
